# Generated by Django 5.0.4 on 2024-09-20 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordr_app', '0002_alter_excelfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excelfile',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
